### ISSUE TITLE
Does not work with routing contollers 0.8

### ISSUE THREAD

**Issue by edward-soetiono-asto** [epiphone/routing-controllers-openapi#33]
Compilation error when using routing controllers 0.8.0, works ok with 0.7.7

**Comment by epiphone** [comment]
Published a fix in `1.8.0`. Thanks for the heads-up!
